### ISSUE TITLE
installExtension reports error regarding electron version

### ISSUE THREAD

**Issue by justin-hackin** [jonluca/electron-extension-installer#3]
`
[main] (node:22542) UnhandledPromiseRejectionWarning: Error: Version of Electron: 14.0.1 does not match required range >=1.2.1 for extension fmkadmapgofadopljbjfkapdkoienihi
    at Object.installExtension (/xxxxxx/main/dist/index.cjs:15459:15)
`

is thrown when attempting to fix issues with `electron-devtools-installer` using this extension.

**Comment by jonluca** [comment]
Looks like it was an issue with how we were parsing the semver of electron, should be fixed in v1.1.1

**Comment by justin-hackin** [comment]
@jonluca Thanks, I confirmed that this library now works as expected in 1.1.3
