### ISSUE TITLE
allow custom session option

### ISSUE THREAD

**Issue by skdhg** [jonluca/electron-extension-installer#4]
Hello, thanks for developing this library. I have a project that I'm working on, and it uses custom session. I need to install extensions on the custom session rather than the default one. Based on the source code, the target session is hardcoded to be `session.defaultSession` so I am blocked by this. My proposal would be something similar to the following:

```ts
import { installExtension, REACT_DEVELOPER_TOOLS } from "electron-extension-installer";

app.on("ready", async () => {
  await installExtension(REACT_DEVELOPER_TOOLS, {
    loadExtensionOptions: {
      allowFileAccess: true,
    },
    session: optionalSessionTarget
  });
});
```

Types for `ExtensionOptions` can be updated to

```diff
export interface ExtensionOptions {
  /**
   * Ignore whether the extension is already downloaded and redownload every time
   */
  forceDownload?: boolean;
  /**
   * Options passed to session.loadExtension
   */
  loadExtensionOptions?: LoadExtensionOptions;
+  /* todo: doc */
+  session?: string | Electron.Session;
}
```

The `session` property should accept a string or session object. Sometimes we use partition key and not the session object itself so it would be better to support both. It could be resolved in this way:

```ts
// if session option is a string, resolve string to session object else pick whichever is available
const targetSession = typeof options.session === 'string' ? session.fromPartition(options.session) : options.session ?? session.defaultSession;
```

**Comment by jonluca** [comment]
LGTM! Thanks for the PR!
